### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by cbix** [alefnull/alefsbits#1]
According to the `plugin.json` this project is licensed under `GPL-3.0-or-later`, could you please also add a file containing the full license text? Thanks :)

**Comment by dromer** [comment]
One potential issue I see is with `simplex vco`.

It says `based heavily on the Simplex Oscillator from TinyTricks` << and that project is `GPL-3.0-only`.

**Comment by alefnull** [comment]
i did remove the simplex vco because i was never going to get around to finishing it anyway, on top of the licensing issues. i will also add a LICENSE file to the repo ASAP. thank you for the suggestion and sorry for the delayed response :)
