### ISSUE TITLE
Shift CV range unexpected

### ISSUE THREAD

**Issue by spacejoey86** [alefnull/alefsbits#2]
On the shift module, the CV inputs work with 0-1V inputs, anything higher is treated the same as 1V.
https://github.com/alefnull/alefsbits/blob/ede2cdad37c29298b4baf4400e8549dbc596358e/src/shift.cpp#L99
This could be fixed by dividing the input by 10 so it follows the voltage standards [here](https://vcvrack.com/manual/VoltageStandards)

ie: 
`chance = clamp(chance / 10 * inputs[REGISTER_1_INPUT + i].getVoltage(), 0.f, 1.f); `

**Comment by alefnull** [comment]
thanks! i'll look into making this change for the next library update :)

**Comment by alefnull** [comment]
> chance = clamp(chance / 10 * inputs[REGISTER_1_INPUT + i].getVoltage(), 0.f, 1.f);

i'm assuming you meant to divide the input voltage by 10, not the chance variable?
