### ISSUE TITLE
poly play feature request: ramp output tracking position

### ISSUE THREAD

**Issue by glocke01** [alefnull/alefsbits#3]
first, thanks for all your awesome work.

I'd love a "phasor" output from 0-10V or whatever that ramps linearly with position in the sample. There are two functions this would enable:

1. use waveshaping or a scanned function/sequencer (e.g. ShapeMaster, BZ-Mapper, PdArray) for fading
2. auto-retrigger using a Polyphonic Min/Max to track when the last triggered sample approaches the end

Both of these can be done if you "know in advance" what the sample length is, but having it automatic is nice, innit?

Thanks again!

**Comment by alefnull** [comment]
thanks for the nice comment! and also thanks for the feature request. i'll look into it and see if i can make it happen. 😄

**Comment by alefnull** [comment]
so i gave it a shot. try this build and see if it works out the way you hoped. let me know if you run into any issues 😄 

[https://github.com/alefnull/alefsbits/releases/tag/2.5.0-7448254](https://github.com/alefnull/alefsbits/releases/tag/2.5.0-7448254)

**Comment by glocke01** [comment]
thanks I'll try it and get back to you.

**Comment by alefnull** [comment]
it's been a couple of weeks, and i haven't found any issues in my own testing of this feature, so i'm going to go ahead and close this issue, and then i'll be submitting the change to the library, so it should be updated within the next week or so, i would guess.

thanks again for the suggestion :)
