### ISSUE TITLE
Random of the 8 steps sequencer

### ISSUE THREAD

**Issue by maximedangles** [alefnull/alefsbits#8]
Hello,

the random function doesn't seam to work proprely with the range you choose.
For exemple :
i choose the range -2V to 2V, but the steps randomize from -5v to 5v.
thanks for your work !

**Comment by alefnull** [comment]
thanks for the notice. i've taken a bit of a step back from working on these projects recently due to some personal issues that recently came up, but i'll try to take a look into this as soon as i am able to.

**Comment by alefnull** [comment]
i just had a little bit of free time and decided to poke around in steps to find out what was going wrong. i've fixed the issue, but i'm not sure when it will make it to the library, as i still have other things on my priority list. for now, if you're interested, you are welcome to grab the latest pre-release build i just ran that includes the fix. you'll just have to manually download and drop the plugin in your plugins folder.

[https://github.com/alefnull/alefsbits/releases/tag/2.5.41-0be11c6](https://github.com/alefnull/alefsbits/releases/tag/2.5.41-0be11c6)

**Comment by maximedangles** [comment]
great ! it works perfectly here now ;) thank you !
